#!/bin/sh
#
# Executed by startx

export XSECURELOCK_AUTH_BACKGROUND_COLOR=#1d1f21
export XSECURELOCK_AUTH_FOREGROUND_COLOR=#007fff
export XSECURELOCK_PASSWORD_PROMPT=disco
export XSECURELOCK_COMPOSITE_OBSCURER=0
export XSECURELOCK_NO_COMPOSITE=1

~/.fehbg &
picom &
nm-applet &
redshift -P &
